class BibleLanguageOption {
  const BibleLanguageOption({
    required this.code,
    required this.nativeLabel,
    required this.englishLabel,
    required this.fallbackSourceLabel,
    required this.fallbackVersionTitle,
    required this.fallbackAbbreviation,
    required this.preferredVersionKeywords,
    required this.fontFamilyFallback,
    this.fallbackBibleId,
    this.fallbackAudioBibleId,
  });

  final String code;
  final String nativeLabel;
  final String englishLabel;
  final int? fallbackBibleId;
  final int? fallbackAudioBibleId;
  final String fallbackSourceLabel;
  final String fallbackVersionTitle;
  final String fallbackAbbreviation;
  final List<String> preferredVersionKeywords;
  final List<String> fontFamilyFallback;
}

const List<BibleLanguageOption> bibleLanguageOptions = <BibleLanguageOption>[
  BibleLanguageOption(
    code: 'en',
    nativeLabel: 'English',
    englishLabel: 'English',
    fallbackBibleId: 111,
    fallbackAudioBibleId: 111,
    fallbackSourceLabel: 'NIV / Bible.com',
    fallbackVersionTitle: 'New International Version',
    fallbackAbbreviation: 'NIV',
    preferredVersionKeywords: <String>['NIV', 'Bible.com', 'NKJV', 'KJV'],
    fontFamilyFallback: <String>['Georgia', 'Times New Roman', 'Noto Serif'],
  ),
  BibleLanguageOption(
    code: 'te',
    nativeLabel: '\u0c24\u0c46\u0c32\u0c41\u0c17\u0c41',
    englishLabel: 'Telugu',
    fallbackBibleId: 1787,
    fallbackAudioBibleId: 1787,
    fallbackSourceLabel: 'TELUBSI / Bible.com',
    fallbackVersionTitle: 'O.V. Bible (BSI)',
    fallbackAbbreviation: 'TELUBSI',
    preferredVersionKeywords: <String>[
      'TELUBSI',
      'BSI',
      'O.V.',
      'TELUGU',
      '\u0c24\u0c46\u0c32\u0c41\u0c17\u0c41',
    ],
    fontFamilyFallback: <String>[
      'Noto Serif Telugu',
      'Noto Sans Telugu',
      'Nirmala UI',
      'Gautami',
    ],
  ),
  BibleLanguageOption(
    code: 'hi',
    nativeLabel: '\u0939\u093f\u0928\u094d\u0926\u0940',
    englishLabel: 'Hindi',
    fallbackBibleId: 1683,
    fallbackAudioBibleId: 1683,
    fallbackSourceLabel: 'HINOVBSI / Bible.com',
    fallbackVersionTitle: 'O.V. Bible (BSI)',
    fallbackAbbreviation: 'HINOVBSI',
    preferredVersionKeywords: <String>[
      'HINOVBSI',
      'BSI',
      'O.V.',
      'HINDI',
      '\u0939\u093f\u0928\u094d\u0926\u0940',
    ],
    fontFamilyFallback: <String>[
      'Noto Serif Devanagari',
      'Noto Sans Devanagari',
      'Nirmala UI',
      'Mangal',
    ],
  ),
  BibleLanguageOption(
    code: 'ta',
    nativeLabel: '\u0ba4\u0bae\u0bbf\u0bb4\u0bcd',
    englishLabel: 'Tamil',
    fallbackBibleId: 339,
    fallbackAudioBibleId: 339,
    fallbackSourceLabel: 'TAOVBSI / Bible.com',
    fallbackVersionTitle: 'O.V. Bible (BSI)',
    fallbackAbbreviation: 'TAOVBSI',
    preferredVersionKeywords: <String>[
      'TAOVBSI',
      'TAMBSI',
      'BSI',
      'O.V.',
      'TAMIL',
      '\u0ba4\u0bae\u0bbf\u0bb4\u0bcd',
    ],
    fontFamilyFallback: <String>[
      'Noto Serif Tamil',
      'Noto Sans Tamil',
      'Nirmala UI',
      'Latha',
    ],
  ),
  BibleLanguageOption(
    code: 'kn',
    nativeLabel: '\u0c95\u0ca8\u0ccd\u0ca8\u0ca1',
    englishLabel: 'Kannada',
    fallbackBibleId: 1684,
    fallbackAudioBibleId: 1898,
    fallbackSourceLabel: 'KANJV-BSI / Bible.com',
    fallbackVersionTitle: 'J.V. Bible (BSI)',
    fallbackAbbreviation: 'KANJV-BSI',
    preferredVersionKeywords: <String>[
      'KANJV-BSI',
      'KANBSI',
      'BSI',
      'J.V.',
      'KANNADA',
      '\u0c95\u0ca8\u0ccd\u0ca8\u0ca1',
    ],
    fontFamilyFallback: <String>[
      'Noto Serif Kannada',
      'Noto Sans Kannada',
      'Nirmala UI',
      'Tunga',
    ],
  ),
  BibleLanguageOption(
    code: 'ml',
    nativeLabel: '\u0d2e\u0d32\u0d2f\u0d3e\u0d33\u0d02',
    englishLabel: 'Malayalam',
    fallbackBibleId: 1693,
    fallbackAudioBibleId: 1693,
    fallbackSourceLabel: 'MALOVBSI / Bible.com',
    fallbackVersionTitle: 'O.V. Bible (BSI)',
    fallbackAbbreviation: 'MALOVBSI',
    preferredVersionKeywords: <String>[
      'MALOVBSI',
      'MALBSI',
      'BSI',
      'O.V.',
      'MALAYALAM',
      '\u0d2e\u0d32\u0d2f\u0d3e\u0d33\u0d02',
    ],
    fontFamilyFallback: <String>[
      'Noto Serif Malayalam',
      'Noto Sans Malayalam',
      'Nirmala UI',
      'Kartika',
    ],
  ),
  BibleLanguageOption(
    code: 'mr',
    nativeLabel: '\u092e\u0930\u093e\u0920\u0940',
    englishLabel: 'Marathi',
    fallbackBibleId: 1686,
    fallbackAudioBibleId: 1686,
    fallbackSourceLabel: 'MARVBSI / Bible.com',
    fallbackVersionTitle: 'R.V. Bible (BSI)',
    fallbackAbbreviation: 'MARVBSI',
    preferredVersionKeywords: <String>[
      'MARVBSI',
      'MARBSI',
      'BSI',
      'R.V.',
      'MARATHI',
      '\u092e\u0930\u093e\u0920\u0940',
    ],
    fontFamilyFallback: <String>[
      'Noto Serif Devanagari',
      'Noto Sans Devanagari',
      'Nirmala UI',
      'Mangal',
    ],
  ),
  BibleLanguageOption(
    code: 'as',
    nativeLabel: '\u0985\u09b8\u09ae\u09c0\u09af\u09bc\u09be',
    englishLabel: 'Assamese',
    fallbackBibleId: 1979,
    fallbackAudioBibleId: null,
    fallbackSourceLabel: 'IRV-ASM / Bible.com',
    fallbackVersionTitle: 'IRV Assamese 2019',
    fallbackAbbreviation: 'IRV-ASM',
    preferredVersionKeywords: <String>[
      'IRV',
      'ASSAMESE',
      '\u0985\u09b8\u09ae\u09c0\u09af\u09bc\u09be',
    ],
    fontFamilyFallback: <String>[
      'Noto Serif Bengali',
      'Noto Sans Bengali',
      'Vrinda',
    ],
  ),
  BibleLanguageOption(
    code: 'br',
    nativeLabel: 'Bodo',
    englishLabel: 'Bodo',
    fallbackBibleId: null,
    fallbackAudioBibleId: null,
    fallbackSourceLabel: 'Bible.com',
    fallbackVersionTitle: 'Bodo Bible',
    fallbackAbbreviation: 'BODO',
    preferredVersionKeywords: <String>['BODO', 'BRX'],
    fontFamilyFallback: <String>[
      'Noto Serif Devanagari',
      'Noto Sans Devanagari',
      'Nirmala UI',
      'Mangal',
    ],
  ),
  BibleLanguageOption(
    code: 'kok',
    nativeLabel: '\u0915\u094b\u0902\u0915\u0923\u0940',
    englishLabel: 'Konkani',
    fallbackBibleId: 1866,
    fallbackAudioBibleId: null,
    fallbackSourceLabel: 'GOABSI / Bible.com',
    fallbackVersionTitle: 'Novo Korar NT (BSI)',
    fallbackAbbreviation: 'GOABSI',
    preferredVersionKeywords: <String>[
      'KONKANI',
      'GOA',
      'BSI',
      '\u0915\u094b\u0902\u0915\u0923\u0940',
    ],
    fontFamilyFallback: <String>[
      'Noto Serif Devanagari',
      'Noto Sans Devanagari',
      'Nirmala UI',
      'Mangal',
    ],
  ),
  BibleLanguageOption(
    code: 'mni',
    nativeLabel: '\u09ae\u09c7\u0987\u09a4\u09c7\u0987',
    englishLabel: 'Manipuri',
    fallbackBibleId: null,
    fallbackAudioBibleId: null,
    fallbackSourceLabel: 'Bible.com',
    fallbackVersionTitle: 'Manipuri Bible',
    fallbackAbbreviation: 'MNI',
    preferredVersionKeywords: <String>['MANIPURI', 'MEITEI', 'MNI'],
    fontFamilyFallback: <String>[
      'Noto Serif Bengali',
      'Noto Sans Bengali',
      'Vrinda',
    ],
  ),
  BibleLanguageOption(
    code: 'or',
    nativeLabel: '\u0b13\u0b21\u0b3c\u0b3f\u0b06',
    englishLabel: 'Odia',
    fallbackBibleId: null,
    fallbackAudioBibleId: null,
    fallbackSourceLabel: 'Bible.com',
    fallbackVersionTitle: 'Odia Bible',
    fallbackAbbreviation: 'ORI',
    preferredVersionKeywords: <String>['ODIA', 'ORIYA', 'ORI'],
    fontFamilyFallback: <String>[
      'Noto Serif Oriya',
      'Noto Sans Oriya',
      'Kalinga',
    ],
  ),
  BibleLanguageOption(
    code: 'pa',
    nativeLabel: '\u0a2a\u0a70\u0a1c\u0a3e\u0a2c\u0a40',
    englishLabel: 'Punjabi',
    fallbackBibleId: 1884,
    fallbackAudioBibleId: null,
    fallbackSourceLabel: 'IRV-PAN / Bible.com',
    fallbackVersionTitle: 'IRV Punjabi',
    fallbackAbbreviation: 'IRV-PAN',
    preferredVersionKeywords: <String>[
      'IRV',
      'PUNJABI',
      '\u0a2a\u0a70\u0a1c\u0a3e\u0a2c\u0a40',
    ],
    fontFamilyFallback: <String>[
      'Noto Serif Gurmukhi',
      'Noto Sans Gurmukhi',
      'Raavi',
    ],
  ),
  BibleLanguageOption(
    code: 'bn',
    nativeLabel: '\u09ac\u09be\u0982\u09b2\u09be',
    englishLabel: 'Bengali',
    fallbackBibleId: 1681,
    fallbackAudioBibleId: null,
    fallbackSourceLabel: 'BENOVBSI / Bible.com',
    fallbackVersionTitle: 'O.V. Bible (BSI)',
    fallbackAbbreviation: 'BENOVBSI',
    preferredVersionKeywords: <String>[
      'BENOVBSI',
      'BSI',
      'O.V.',
      'BENGALI',
      '\u09ac\u09be\u0982\u09b2\u09be',
    ],
    fontFamilyFallback: <String>[
      'Noto Serif Bengali',
      'Noto Sans Bengali',
      'Vrinda',
    ],
  ),
  BibleLanguageOption(
    code: 'ne',
    nativeLabel: '\u0928\u0947\u092a\u093e\u0932\u0940',
    englishLabel: 'Nepali',
    fallbackBibleId: 1711,
    fallbackAudioBibleId: null,
    fallbackSourceLabel: 'NEPSN / Bible.com',
    fallbackVersionTitle: 'Saral Nepali Bible',
    fallbackAbbreviation: 'NEPSN',
    preferredVersionKeywords: <String>[
      'NEPALI',
      'SARAL',
      '\u0928\u0947\u092a\u093e\u0932\u0940',
    ],
    fontFamilyFallback: <String>[
      'Noto Serif Devanagari',
      'Noto Sans Devanagari',
      'Nirmala UI',
      'Mangal',
    ],
  ),
  BibleLanguageOption(
    code: 'doi',
    nativeLabel: '\u0921\u094b\u0917\u0930\u0940',
    englishLabel: 'Dogri',
    fallbackBibleId: null,
    fallbackAudioBibleId: null,
    fallbackSourceLabel: 'Bible.com',
    fallbackVersionTitle: 'Dogri Bible',
    fallbackAbbreviation: 'DOI',
    preferredVersionKeywords: <String>['DOGRI', 'DOI'],
    fontFamilyFallback: <String>[
      'Noto Serif Devanagari',
      'Noto Sans Devanagari',
      'Nirmala UI',
      'Mangal',
    ],
  ),
  BibleLanguageOption(
    code: 'ks',
    nativeLabel: '\u06a9\u0672\u0634\u064f\u0631',
    englishLabel: 'Kashmiri',
    fallbackBibleId: null,
    fallbackAudioBibleId: null,
    fallbackSourceLabel: 'Bible.com',
    fallbackVersionTitle: 'Kashmiri Bible',
    fallbackAbbreviation: 'KAS',
    preferredVersionKeywords: <String>['KASHMIRI', 'KAS'],
    fontFamilyFallback: <String>[
      'Noto Nastaliq Urdu',
      'Noto Serif Devanagari',
      'Nirmala UI',
    ],
  ),
  BibleLanguageOption(
    code: 'gu',
    nativeLabel: '\u0a97\u0ac1\u0a9c\u0ab0\u0abe\u0aa4\u0ac0',
    englishLabel: 'Gujarati',
    fallbackBibleId: null,
    fallbackAudioBibleId: null,
    fallbackSourceLabel: 'Bible.com',
    fallbackVersionTitle: 'Gujarati Bible',
    fallbackAbbreviation: 'GUJ',
    preferredVersionKeywords: <String>[
      'GUJARATI',
      'GUJ',
      'BSI',
      '\u0a97\u0ac1\u0a9c\u0ab0\u0abe\u0aa4\u0ac0',
    ],
    fontFamilyFallback: <String>[
      'Noto Serif Gujarati',
      'Noto Sans Gujarati',
      'Shruti',
    ],
  ),
  BibleLanguageOption(
    code: 'sd',
    nativeLabel: '\u0633\u0646\u0688\u064a',
    englishLabel: 'Sindhi',
    fallbackBibleId: 722,
    fallbackAudioBibleId: null,
    fallbackSourceLabel: 'SNDCL / Bible.com',
    fallbackVersionTitle: 'Common Language NT',
    fallbackAbbreviation: 'SNDCL',
    preferredVersionKeywords: <String>['SINDHI', 'SND'],
    fontFamilyFallback: <String>[
      'Noto Nastaliq Urdu',
      'Noto Serif Devanagari',
      'Nirmala UI',
    ],
  ),
  BibleLanguageOption(
    code: 'sa',
    nativeLabel: '\u0938\u0902\u0938\u094d\u0915\u0943\u0924\u092e\u094d',
    englishLabel: 'Sanskrit',
    fallbackBibleId: null,
    fallbackAudioBibleId: null,
    fallbackSourceLabel: 'Bible.com',
    fallbackVersionTitle: 'Sanskrit Bible',
    fallbackAbbreviation: 'SAN',
    preferredVersionKeywords: <String>['SANSKRIT', 'SAN'],
    fontFamilyFallback: <String>[
      'Noto Serif Devanagari',
      'Noto Sans Devanagari',
      'Nirmala UI',
      'Mangal',
    ],
  ),
];

final Map<String, BibleLanguageOption> bibleLanguageByCode =
    <String, BibleLanguageOption>{
  for (final BibleLanguageOption option in bibleLanguageOptions)
    option.code: option,
};

BibleLanguageOption bibleLanguageForCode(String code) =>
    bibleLanguageByCode[code.trim().toLowerCase()] ??
    bibleLanguageOptions.first;
